### ISSUE TITLE
Como Admin, eu quero receber uma mensagem quando o servidor estiver indisponível para que retorne em outro momento

### ISSUE THREAD

**Issue by AlexsandroCampos** [ifspcodelab/gestao-estagios-backend#109]
Atualmente não é apresentada uma mensagem na lista de campus quando o servidor está indisponível.

E isso é um problema, pois o usuário não sabe a sua situação no sistema.

Critérios de aceitação:

- [ ] Deve tentar fazer a requisição novamente pelo menos uma vez quando for capturado um erro
- [ ] Deve apresentar uma mensagem de erro quando não for possível carregar a lista de campus
- [ ] A mensagem de erro deve ter o texto "Erro ao carregar os campus"

**Comment by domingoslatorre** [comment]
https://blog.angular-university.io/rxjs-error-handling/
