### ISSUE TITLE
Incluir campo de busca na documentação

### ISSUE THREAD

**Issue by domingoslatorre** [ifspcodelab/gestao-estagios-backend#4]
Incluir campo de busca na documentação do docsifyjs.

**Comment by junnmu** [comment]
Encontrei como fazer isso [nessa parte da documentação do docsify](https://docsify.js.org/#/plugins?id=full-text-search). Talvez tenhamos que voltar aqui depois se acrescentarmos novas seções na documentação do projeto

**Comment by domingoslatorre** [comment]
E nessa parte da doc mesmo. Vou revisar seu pull request.
